test:
  adapter: postgresql
  encoding: unicode
  database: training_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 25

development:
  adapter: postgresql
  encoding: unicode
  database: training_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 25
